### ISSUE TITLE
ccxt.base.errors.ExchangeNotAvailable

### ISSUE THREAD

**Issue by 0jessica0** [freqtrade/freqtrade#10667]
There is a similar problems that has been closed, but there is no solution about it.
https://github.com/freqtrade/freqtrade/issues/10311
## Describe your environment

  * Operating system: ____windows（no docker）
  * Python Version: _____3.11.9 (python -V)
  * CCXT version: _____4.3.98 (pip freeze | grep ccxt)
  * Freqtrade Version: ____2024.9 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)
  
## Your question

When I tried the basic function
`freqtrade trade --config user_data/config.json --strategy SampleStrategy`

I got this log
```
2024-09-16 17:34:30,261 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-09-16 17:34:30,261 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.98
2024-09-16 17:34:30,262 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpsProxy': 'http://192.168.1.100:8080', 'wsProxy': 'http://192.168.1.100:8080'}
2024-09-16 17:34:30,266 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpsProxy': 'http://192.168.1.100:8080', 'wsProxy': 'http://192.168.1.100:8080'}
2024-09-16 17:34:30,272 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap', 'brokerId': 'ffb5405ad327SUDE'}, 'httpsProxy': 'http://192.168.1.100:8080', 'wsProxy': 'http://192.168.1.100:8080'}
2024-09-16 17:34:30,277 - freqtrade.exchange.exchange - INFO - Using Exchange "OKX"
2024-09-16 17:34:35,470 - freqtrade.exchange.exchange - ERROR - Could not load markets.
Traceback (most recent call last):
  File "E:\app\anaconda\envs\freqtrade\Lib\asyncio\selector_events.py", line 999, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 199, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 1422, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\client_reqrep.py", line 999, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 10054] An existing connection was forcibly closed by the remote host

Traceback (most recent call last):
  File "E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\freqtrade\exchange\exchange.py", line 655, in reload_markets
    self._markets = self._load_async_markets(reload=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\freqtrade\exchange\exchange.py", line 628, in _load_async_markets
    markets = self.loop.run_until_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 276, in load_markets
    raise e
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 272, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 262, in load_markets_helper
    markets = await self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\okx.py", line 1393, in fetch_markets
    promises = await asyncio.gather(*promises)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\okx.py", line 1557, in fetch_markets_by_type
    response = await self.publicGetPublicInstruments(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 848, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 844, in fetch2
    raise e
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 835, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 237, in fetch
    raise ExchangeNotAvailable(details) from e
ccxt.base.errors.ExchangeNotAvailable: okx GET https://www.okx.com/api/v5/public/instruments?instType=SPOT
2024-09-16 17:34:35,478 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
```
here is my config
```

{
    "$schema": "https://schema.freqtrade.io/schema.json",
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "okx",
        "key": "",
        "secret": "",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
}
```
I did use VPN to change my IP address to US. 
When I type `netsh winhttp show proxy` in CMD, I got 
```
Current WinHTTP proxy settings:

    Direct access (no proxy server).
```
when I type `curl https://www.okx.com/api/v5/public/instruments?instType=SPOT`,  I get the transaction data.

So what should I put in the ccxt_config, so that I can get the market data?

BTW, can get in '127.0.0.1:8080', before the bot starts?

Thanks

**Comment by xmatthias** [comment]
There is solution for #10311 (last comment) - which is to properly configure the proxy without inventing non-existent configuration keys.

It does however appear to be the reverse problem (proxy is not used) to yours (proxy is used but shouldn't).

Your log suggests that you're using a proxy to connect to OKX - which is not shown in the configuration - so either you removed "too much"  from the configuration - or you're looking at the wrong configuration all along.

At any rate, your curl command is therefore incorrect and won't match requests the bot makes. 
To match the request from the bot - you'll have to add a `--proxy http://192.168.1.100:8080` to it (though you're on windows - not sure if windows version of curl properly supports proxies - but it'll be more like `-proxy http://192.168.1.100:8080` (one dash) ).

> BTW, can get in '127.0.0.1:8080', before the bot starts?

The API starts once available information is available. If the exchange can't initialize, there's no point to get the API up and running.

You can run `freqtrade webserver` - but that will NOT allow you to do trading, and will instead provide other options (most of which will still require the exchange to be initialized - so without that, your options will be pretty limited.

**Comment by 0jessica0** [comment]
nah, it still doesn't work

This is my new config

I tried both "http://127.0.0.1:7890" and "http://192.168.1.100:8080".
None of them works.

```
{
    "$schema": "https://schema.freqtrade.io/schema.json",
    "max_open_trades": 5,
    "stake_currency": "USDT",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "USD",
    "dry_run": true,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "futures",
    "margin_mode": "isolated",
    "unfilledtimeout": {
        "entry": 10,
        "exit": 10,
        "exit_timeout_count": 0,
        "unit": "minutes"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "okx",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "httpsProxy": "http://127.0.0.1:7890"
        },
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
    "telegram": {
        "enabled": true,
        "token": "",
        "chat_id": ""
    },
    "bot_name": "freqtrade",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 5
    }
}
```

Is the ccxt_config only thing that needs to be changed?

Now the log is different, but the error is the same:
```
2024-09-16 20:55:42,149 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-09-16 20:55:42,149 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.98
2024-09-16 20:55:42,149 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpsProxy': 'http://127.0.0.1:7890'}
2024-09-16 20:55:42,153 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpsProxy': 'http://127.0.0.1:7890'}
2024-09-16 20:55:42,157 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap', 'brokerId': 'ffb5405ad327SUDE'}, 'httpsProxy': 'http://127.0.0.1:7890'}
2024-09-16 20:55:42,161 - freqtrade.exchange.exchange - INFO - Using Exchange "OKX"
2024-09-16 20:55:44,401 - freqtrade.exchange.exchange - ERROR - Could not load markets.
Traceback (most recent call last):
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 1073, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohappyeyeballs\impl.py", line 104, in start_connection
    raise first_exception
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohappyeyeballs\impl.py", line 81, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohappyeyeballs\impl.py", line 166, in _connect_sock
    await loop.sock_connect(sock, address)
  File "E:\app\anaconda\envs\freqtrade\Lib\asyncio\selector_events.py", line 638, in sock_connect
    return await fut
           ^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\asyncio\selector_events.py", line 678, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 10061] Connect call failed ('127.0.0.1', 7890)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 199, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 973, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 1375, in _create_proxy_connection
    transport, proto = await self._create_direct_connection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\aiohttp\connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientProxyConnectionError: Cannot connect to host 127.0.0.1:7890 ssl:default [Connect call failed ('127.0.0.1', 7890)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\freqtrade\exchange\exchange.py", line 655, in reload_markets
    self._markets = self._load_async_markets(reload=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\freqtrade\exchange\exchange.py", line 628, in _load_async_markets
    markets = self.loop.run_until_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 276, in load_markets
    raise e
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 272, in load_markets
    result = await self.markets_loading
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 262, in load_markets_helper
    markets = await self.fetch_markets(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\okx.py", line 1393, in fetch_markets
    promises = await asyncio.gather(*promises)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\okx.py", line 1557, in fetch_markets_by_type
    response = await self.publicGetPublicInstruments(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 848, in request
    return await self.fetch2(path, api, method, params, headers, body, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 844, in fetch2
    raise e
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 835, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\app\anaconda\envs\freqtrade\Lib\site-packages\ccxt\async_support\base\exchange.py", line 237, in fetch
    raise ExchangeNotAvailable(details) from e
ccxt.base.errors.ExchangeNotAvailable: okx GET https://www.okx.com/api/v5/public/instruments?instType=FUTURES
2024-09-16 20:55:44,408 - freqtrade - ERROR - Could not load markets, therefore cannot start. Please investigate the above error for more details.
```

What should I try next?

Plus the curl command
I changed to `curl https://www.okx.com/api/v5/public/instruments?instType=FUTURES -proxy http://192.168.1.100:8080`
I can still get the market data.
(ps  I don't what the curl command does exactly. But when I use curl command, I can get market data, but in the bot, it shows an error. It is a problem right?)

**Comment by xmatthias** [comment]
you're setting httpsProxy - which implies that your proxy talks https - which apparently it doesn't (that's what the error says).

If it works with the curl command as is - your best bet is to try and _remove_ the proxy configuration completely - as the proxy seems unnecessary in this case.

While proxy-configuration is something that i know works as i use it myself from time to time (including in CI) - it's not something we can be of great assistance, as it's your environment - which will 100% be different from what i got.

**Comment by 0jessica0** [comment]
After I change a VPN and open the TUN mode, it appears that the problem is solved, but another one shows up.
```
(freqtrade) E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade>freqtrade trade --config user_data/config.json --strategy SampleStrategy
2024-09-17 08:40:35,765 - freqtrade - INFO - freqtrade 2024.9-dev-e96928588
2024-09-17 08:40:36,054 - freqtrade.worker - INFO - Starting worker 2024.9-dev-e96928588
2024-09-17 08:40:36,054 - freqtrade.configuration.load_config - INFO - Using config: user_data/config.json ...
2024-09-17 08:40:36,054 - freqtrade.loggers - INFO - Verbosity set to 0
2024-09-17 08:40:36,055 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2024-09-17 08:40:36,055 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2024-09-17 08:40:36,055 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2024-09-17 08:40:36,055 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 5 ...
2024-09-17 08:40:36,056 - freqtrade.configuration.configuration - INFO - Using user-data directory: E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\user_data ...
2024-09-17 08:40:36,056 - freqtrade.configuration.configuration - INFO - Using data directory: E:\app\Nutstore\我的坚果 云\区块链\freqtrade\freqtrade\user_data\data\okx ...
2024-09-17 08:40:36,056 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-09-17 08:40:36,061 - freqtrade.exchange.check_exchange - INFO - Exchange "okx" is officially supported by the Freqtrade development team.
2024-09-17 08:40:36,061 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-09-17 08:40:36,071 - freqtrade.resolvers.iresolver - WARNING - Could not import E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\user_data\strategies\GodStra.py due to 'No module named 'ta''
2024-09-17 08:40:36,071 - freqtrade.resolvers.iresolver - WARNING - Could not import E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\user_data\strategies\Heracles.py due to 'No module named 'ta''
2024-09-17 08:40:36,157 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from 'E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\user_data\strategies\sample_strategy.py'...
2024-09-17 08:40:36,158 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-09-17 08:40:36,159 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-09-17 08:40:36,159 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-09-17 08:40:36,159 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-09-17 08:40:36,160 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 5.
2024-09-17 08:40:36,160 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2024-09-17 08:40:36,160 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-09-17 08:40:36,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2024-09-17 08:40:36,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-09-17 08:40:36,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-09-17 08:40:36,161 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-09-17 08:40:36,162 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-09-17 08:40:36,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-09-17 08:40:36,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2024-09-17 08:40:36,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-09-17 08:40:36,163 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-09-17 08:40:36,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-09-17 08:40:36,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-09-17 08:40:36,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2024-09-17 08:40:36,164 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-09-17 08:40:36,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-09-17 08:40:36,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-09-17 08:40:36,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-09-17 08:40:36,165 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-09-17 08:40:36,166 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-09-17 08:40:36,166 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-09-17 08:40:36,166 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
2024-09-17 08:40:36,166 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
2024-09-17 08:40:36,167 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 5
2024-09-17 08:40:36,167 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-09-17 08:40:36,169 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2024-09-17 08:40:36,169 - freqtrade.exchange.exchange - INFO - Using CCXT 4.3.98
2024-09-17 08:40:36,170 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpsProxy': 'http://127.0.0.1:7890'}
2024-09-17 08:40:36,174 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}, 'httpsProxy': 'http://127.0.0.1:7890'}
2024-09-17 08:40:36,179 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap', 'brokerId': 'ffb5405ad327SUDE'}, 'httpsProxy': 'http://127.0.0.1:7890'}
2024-09-17 08:40:36,184 - freqtrade.exchange.exchange - INFO - Using Exchange "OKX"
2024-09-17 08:40:37,453 - freqtrade.exchange.exchange - INFO - Using cached leverage_tiers.
2024-09-17 08:40:37,453 - freqtrade.exchange.exchange - INFO - Done initializing 191 markets.
2024-09-17 08:40:37,464 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Okx'...
2024-09-17 08:40:37,500 - freqtrade.wallets - INFO - Wallets synced.
2024-09-17 08:40:37,976 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2024-09-17 08:40:38,295 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 127.0.0.1:8080
2024-09-17 08:40:38,295 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-09-17 08:40:38,370 - uvicorn.error - INFO - Started server process [16712]
2024-09-17 08:40:38,370 - uvicorn.error - INFO - Waiting for application startup.
2024-09-17 08:40:38,371 - uvicorn.error - INFO - Application startup complete.
2024-09-17 08:40:38,371 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2024-09-17 08:40:38,379 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from 'E:\app\Nutstore\我的坚果云\区块链\freqtrade\freqtrade\freqtrade\plugins\pairlist\VolumePairList.py'...
2024-09-17 08:40:38,379 - freqtrade - ERROR - Exchange does not support dynamic whitelist in this configuration. Please edit your config and either remove Volumepairlist, or switch to using candles. and restart the bot.
```
Does it mean that I get the data?

here is my config.
```
"exchange": {
        "name": "okx",
        "key": "",
        "secret": "",
        "ccxt_config": {
            "httpsProxy": "http://127.0.0.1:7890"
        },
        "ccxt_async_config": {},
        "pair_whitelist": [
        ],
        "pair_blacklist": [
        ]
    },
    "pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 20,
            "sort_key": "quoteVolume",
            "min_value": 0,
            "refresh_period": 1800
        }
    ],
```

How can I solve the 'Exchange does not support dynamic whitelist in this configuration' problem?


-----------------------------------------------------
nvm, here is the solution.
[https://github.com/freqtrade/freqtrade/issues/7130](url)

------------------------------------------------------
The command `freqtrade trade --config user_data/config.json --strategy SampleStrategy` is used to run the bot and do stimulated trading right?  It doesn't create any backtest results correct?

**Comment by xmatthias** [comment]
essentially your problem was then an incorrectly configured VPN? (I still don't really get why you need both a VPN and a proxy - but that's a different topic).


> The command freqtrade trade --config user_data/config.json --strategy SampleStrategy is used to run the bot and do stimulated trading right? It doesn't create any backtest results correct?

no it doesn't.
for backtesting - you'll need to download data - and then run `freqtrade backtesting [...]`.

**Comment by YangShuai-uestc** [comment]
I have encountered the same problem. Please help me

**Comment by 0jessica0** [comment]
> I have encountered the same problem. Please help me

Hi, I am not sure where you at. I am in China. There are two solutions to this problem. One is to rent a server in Japan or HK. Another is that if you are using Clash VPN, turn on the TUN mode. These are two methods of solving this problem. Hope this can help.

**Comment by YangShuai-uestc** [comment]
thanks, i am in China, It can run once I deploy it to Google Cloud. If possible, we can add each other on WeChat and communicate together.

**Comment by YangShuai-uestc** [comment]
I guess you're also Chinese. Could you tell me that if the system proxy of Clash is turned on, should I use the rule - based mode or the global mode when opening the TUN mode?
![Image](https://github.com/user-attachments/assets/ac0fdd4a-49ac-4492-9c06-08f1fc08ff28)

**Comment by 0jessica0** [comment]
> I guess you're also Chinese. Could you tell me that if the system proxy of Clash is turned on, should I use the rule - based mode or the global mode when opening the TUN mode? ![Image](https://github.com/user-attachments/assets/ac0fdd4a-49ac-4492-9c06-08f1fc08ff28)

![Image](https://github.com/user-attachments/assets/0e827696-78dc-4c24-8e1a-7324baae7670)
This is what I did. After I turned on, I can use it normally.

**Comment by xmatthias** [comment]
I've locked this issue and will be hiding all comments that relate to breaking the law of the country you're in.

while i understand it's an issue, i'd not want this to become a forum to discuss such things.
It'll guide un-informed people towards a path they may not know the risks (iirc, there's quite harsh punishment for trying to circumvent censorship in china).

Thanks for the understanding.
