### ISSUE TITLE
Multiple virtual coins encountered errors during backtesting

### ISSUE THREAD

**Issue by Toney** [freqtrade/freqtrade#12166]
## Describe your environment

  * Operating system: _ Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39___
  * Python Version: __3.12.3___ (`python -V`)
  * CCXT version: _4.4.77____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade 2025.4(`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  __ 
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

freqtrade backtesting -c user_data/config_dev_copy.json --timerange 20240401-20250531 --timeframe-detail 1m --strategy E0V1E_53_Sharpe --eps
  
### Observed Results:

throw new exception

### Relevant code exceptions or logs

  ```
2025-08-26 00:38:08,952 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/mnt/d/freqtrade-2025.4/freqtrade/main.py", line 47, in main
    return_code = args["func"](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/mnt/d/freqtrade-2025.4/freqtrade/commands/optimize_commands.py", line 61, in start_backtesting
    backtesting.start()
  File "/mnt/d/freqtrade-2025.4/freqtrade/optimize/backtesting.py", line 1780, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/freqtrade-2025.4/freqtrade/optimize/backtesting.py", line 1707, in backtest_one_strategy
    results = self.backtest(
              ^^^^^^^^^^^^^^
  File "/mnt/d/freqtrade-2025.4/freqtrade/optimize/backtesting.py", line 1642, in backtest
    for (
  File "/mnt/d/freqtrade-2025.4/freqtrade/optimize/backtesting.py", line 1611, in time_pair_generator
    row = pair_detail_cache[pair][idx]
          ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'ETH/USDT:USDT'

  ```

  ```
{
  "$schema": "https://schema.freqtrade.io/schema.json",
  "max_open_trades": 5,
  "stake_currency": "USDT",
  "trading_mode": "futures",
  "margin_mode": "cross",
  "stake_amount": "unlimited",
  "tradable_balance_ratio": 0.8,
  "fiat_display_currency": "USD",
  "dry_run": true,
  "dry_run_wallet": 10000,
  "cancel_open_orders_on_exit": false,
  "unfilledtimeout": {
    "entry": 5,
    "exit": 10
  },
  "entry_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 1
  },
  "exit_pricing": {
    "price_side": "other",
    "use_order_book": true,
    "order_book_top": 1
  },
  "exchange": {
    "name": "binance",
    "key": "",
    "secret": "",
    "ccxt_config": {
    },
    "order_types": {
      "entry": "limit",
      "exit": "limit"
    },
    "ccxt_async_config": {
    },
    "pair_whitelist": [
      "BTC/USDT:USDT",
      "ETH/USDT:USDT",
      "XRP/USDT:USDT",
      "ADA/USDT:USDT",
      "SOL/USDT:USDT",
      "BNB/USDT:USDT",
      "LINK/USDT:USDT",
      "AVAX/USDT:USDT"
    ],
    "pair_blacklist": [
    ]
  },
  "pairlists": [
    {
      "method": "StaticPairList"
    }
  ],
  "api_server": {
    "enabled": false,
    "listen_ip_address": "127.0.0.1",
    "listen_port": 8084,
    "verbosity": "error",
    "jwt_secret_key": "somethingrandom",
    "CORS_origins": [],
    "username": "1",
    "password": "1"
  },
  "bot_name": "freqtrade",
  "initial_state": "running",
  "force_entry_enable": false,
  "internals": {
    "process_throttle_secs": 5
  }
}

  ```

**Comment by stash86** [comment]
First of all, update to latest stable, and test again. We don't support old versions.

Second, paste the full logs from start to end.

**Comment by Toney** [comment]
I have tried versions 25.7, 25.6, and 25.4, all of which have similar issues

**Comment by stash86** [comment]
Then paste the full logs

**Comment by Toney** [comment]
full logs

[logs.txt](https://github.com/user-attachments/files/21980136/logs.txt)

**Comment by stash86** [comment]
`2025-08-26 10:56:05,829 - freqtrade.data.history.datahandlers.idatahandler - WARNING - ETH/USDT:USDT, futures, 15m, data ends at 2025-05-08 21:15:00`

`2025-08-26 10:56:17,749 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2024-04-01 00:00:00 up to 2025-05-12 23:30:00 (406 days).`

Your ETH data isn't complete. Update your data and try again

**Comment by Toney** [comment]
Very good, the problem has been solved

**Comment by xmatthias** [comment]
despite the error ... we should still not error this way.

should no longer happen with 70ee652be502b558ff7e1907d6393e6acd01c77e  - it'll simply continue with the "main timeframe only" logic once detail data stops.
