### ISSUE TITLE
Insufficient funds to create stop_loss_limit sell order

### ISSUE THREAD

**Issue by yilongwen** [freqtrade/freqtrade#2076]
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: 3.7.3
  * CCXT version: 1.18.738
  * Branch: Develop
  * Last Commit ID: f0206a90b1504c40e74b1c6bae4c719779cdee85
  
## Step 3: Describe the problem:

The bot is not able to create either limit sell order or stoploss limit sell order on regular basis (but not always...). I use unlimited stake amount and max 1 trade, 'full or canceled' for buy orders.

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * The bot finds a different amount to sell than the actual amount.
  * I expected the bot to sync the actual amount before selling.

### Relevant code exceptions or logs:

  ```
  2019-07-31 21:51:30,394 - freqtrade.freqtradebot - WARNING - Amount 57.638000000000005 does not match 57.638
  2019-07-31 21:51:30,394 - freqtrade.freqtradebot - WARNING - Could not update trade amount: Half bought? Amounts don't match
  2019-07-31 21:51:39,712 - freqtrade.freqtradebot - WARNING - Unable to place a stoploss order on exchange: Insufficient funds to create stop_loss_limit sell order on market NEO/USDT. Tried to sell amount 57.638 at rate 6.351 (total 366.058938). Message: binance Account has insufficient balance for requested action.
  ```

**Comment by xmatthias** [comment]
This will require some more information:
* what was the amount (and value) of that pair on the exchange (you should also be able to see this in the trade history for this pair)
* what pair was involved (to help give the numbers more sense)

**Comment by yilongwen** [comment]
- According to trade history: 

2019-07-31 23:51:29 | NEO/USDT | Buy | 11.663 | 25.559 | 0.02555900 NEO | 298.09461700 USDT
----------------------------------------------------------------------------------------------
2019-07-31 23:51:29 | NEO/USDT | Buy | 11.663 | 32.079 | 0.03207900 NEO | 374.13737700 USDT

So the bot bought 25.559 + 32.079 = 57.638. But something funny happened, I typed the equation in Python to get the answer, and it actually gave me 57.638000000000005(which is exactly the warning amount the bot gave).

**Comment by xmatthias** [comment]
hmm yes, happens on my system (3.7.0 / 3.7.3) too.

i'm tempted to say "rounding" ... but that's dangerous too since the correct decimals will depend on the currency (BTC, everything below 10ish will be wrong).

i guess rounding to 14 or 15 decimals would work for most usecases ...

**Comment by hroff-1902** [comment]
@xmatthias 

As I said, do not compare floats for equality. This bug is a result of accumulation of the python float representation error for amounts in the line:
https://github.com/freqtrade/freqtrade/blob/4c005e70861ec7e2294f6097420e0ece289af2d1/freqtrade/freqtradebot.py#L501

A few lines below this result is compared to another float, which was obtained with other calculation approach and, such, can differ in last digits (especially when there are many trades open):
https://github.com/freqtrade/freqtrade/blob/4c005e70861ec7e2294f6097420e0ece289af2d1/freqtrade/freqtradebot.py#L510

The values can be rounded to 8 digits after the point (or to the amount precision reported by the exchange) or better converted to Decimals -- how do you workaround it in other similar places?

All calculations for prices, amounts, costs, etc. should preferably be converted to the operations on Decimals of corresponding precision, but this is a separate huge activity...

**Comment by xmatthias** [comment]
Rounding to 8 digits is problematic if you use BTC as stake.

Using Decimals is a huge pain - we've had them long ago in some very limited places and it created tons of conversation errors (ccxt does not return Decimals, so we need to convert every result ...).

Now i don't remember the exact details (this was over a year ago, right when i started collaborating here), but iirc it did not play nicely with the database.

**Comment by hroff-1902** [comment]
Some considerations:
* ccxt has the `filled` item in the order dict which can be used (and compared with the 'amount' item in the order dict) if you want to detect partially filled order. Without requesting all trades in `get_trades_for_order()` and slicing them for the order_id... This should be much more efficient.
* If you want to detect "half bought" orders, you should probably change `amount != order_amount` to `amount < order_amount` here...
* But this can also fail in case of *fully filled* orders -- right as now, due to float accumulated error, when the value of accumulated amount can become a bit less than order_amount...
* It's quite easy to fix it here locally: calculations in freqtrade and in the ccxt are made on floats (float64) -- that's okay. Completely okay. Just round them to `Decimal(prec)` _before_ comparison. Where prec is the precision of the symbol of the base currency in the pair (i.e. the market precision for the amount value in the ccxt). And compare the Decimals. That's for amounts. For prices, also make calculations in floats and cast them to Decimals with precision equal to price precision reported by the exchange (by ccxt). Same for costs, in other places, everywhere locally, choosing correct precision...
* This also may fail because accumulated error may be more than precision of the Decimal, but this should happen in very rare cases with large amount of trades or other items that are subtracted, multiplied or added...
* The best way is to avoid such conditions. For example, why OperationalException is issued here for partially filled order?

**Comment by xmatthias** [comment]
> ccxt has the filled item in the order dict which can be used (and compared with the 'amount' item in the order dict) if you want to detect partially filled order. Without requesting all trades in get_trades_for_order() and slicing them for the order_id... This should be much more efficient.

Detecting half-filled orders is not really the point of this section, but detecting how much was bought (and how much was subtracted as fee, if any). Since this can be different per trade executed (one order can have 20 trades filling it) - "fillled" will not contain the information we're looking for.

The check throwing the exception is correct(ish), since this section can run multiple times (assume a order is not filled immediately, but partially filled, and the rest filled 2 iterations later). 
Now this does not apply to this case since FOC (full or cancel) is used - but the code still needs to account for this.

> The best way is to avoid such conditions. For example, why OperationalException is issued here for partially filled order?

OperationalException is probably the wrong exception here since, a catchable exception should be used instead.

**Comment by xmatthias** [comment]
this was solved in #2307 - we're now comparing floats correctly for this case.

**Comment by joshuar87** [comment]
Just an FYI I still get the bug:

freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market REN/BTC.Tried to sell amount 2472.525 at rate 8.31e-06. Message: binance Account has insufficient balance for requested action.

sometimes on binance. It seems a stop limit order was already created but it is still trying to create it. Cancelling the order on the exchange allows the bot to repost stop limit order and fixes issue.

**Comment by hroff-1902** [comment]
@joshuar87 pls do not "highjack" old closed issues -- because the original author will be notified in case we need to open the discussion again, which can be non-relevant to the original issue...

pls open a new issue again (do not forger to fill the form with the version of the bot you are using)
