### ISSUE TITLE
impossibe to load strategy

### ISSUE THREAD

**Issue by Nanofernandez** [freqtrade/freqtrade#3144]
I can no run the bot with any strategy.
Always get same error even with the default strategy:

Run this:    freqtrade trade --strategy sample_strategy

Result:
2020-04-06 22:54:25,494 - freqtrade.loggers - INFO - Verbosity set to 0
2020-04-06 22:54:25,496 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2020-04-06 22:54:25,496 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2020-04-06 22:54:25,496 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2020-04-06 22:54:25,496 - freqtrade.configuration.configuration - INFO - Using max_open_trades: inf ...
2020-04-06 22:54:25,497 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/freqtrade/freqtrade/user_data ...
2020-04-06 22:54:25,498 - freqtrade.configuration.configuration - INFO - Using data directory: /home/freqtrade/freqtrade/user_data/data/binance ...
2020-04-06 22:54:25,498 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-04-06 22:54:25,498 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-04-06 22:54:25,498 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-04-06 22:54:25,498 - freqtrade.freqtradebot - INFO - Starting freqtrade 2020.3
2020-04-06 22:54:25,530 - freqtrade - ERROR - Impossible to load Strategy 'sample_strategy'. This class does not exist or contains Python code errors.

Same with any other strategy.
Would like to know if somebody is having same issue and get some recomendation about what to do(?)
Thanks in advance.

**Comment by angrywatermelon69** [comment]
I'm having the exact same issue and still not sure how to work around it -

**Comment by angrywatermelon69** [comment]
I'm sure it has something to do with the __init__ file in the strategy folder because it looks substantially different than the older version I was using which was working.

**Comment by angrywatermelon69** [comment]
Anyone ?

**Comment by xmatthias** [comment]
there is no such thing as `sample_strategy` (unless that's a strategy you created yourself).

You'll need to use `SampleStrategy` (the class-name).

You'll also need to first initialize the userdata directory as described in the installation docs [here](https://www.freqtrade.io/en/latest/installation/#5-initialize-the-configuration) and [here (for docker)](https://www.freqtrade.io/en/latest/docker/#docker-quick-start), and which is also printed at the end of the setup.sh installation script, so you should have encountered this command in the docs by using following any of the 3 installation methods.

```
# Initialize the user_directory
freqtrade create-userdir --userdir user_data/
freqtrade trade --strategy SampleStrategy --userdir user_data/

# --userdir user_data/ is optional for the trade-comand, and only necessary if you're not using the default (which is `user_data`).
```

> Anyone ?

You'll need to exercise patience. People will live in different timezones, and will have other things to do than being always online.
After posting in an issue, give it a few days (depending on the repository also weeks) to get an answer.
Now we try to answer quickly here - which is more or less within a day - pushing will not help with this, thanks for your understanding.

If you instead would have read the documentation, you would have discovered the problem yourself i would think.

**Comment by davideser** [comment]
Hello everybody i have the same problem.


`freqtrade - ERROR - Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors.
`

**Comment by shiftaET** [comment]
> Hello everybody i have the same problem.
> 
> `freqtrade - ERROR - Impossible to load Strategy 'BBRSI'. This class does not exist or contains Python code errors. `
> 
> And if i want to see list of strategys does work...

The UDEMY is old - start again from the beginning! I am having the same issue but I am a few steps (days) ahead, have a coffee, read the docs on here and basically ignore udemy until you get to the point you need to customise the bot. In udemy they make you edit the init file I am seeing in the latest version of this program it is not so?

**Comment by xmatthias** [comment]
well that's the problem - for the udemy course, the authors made the concious decision to use a frozen version (otherwise you'd need to update the course every other week - so a understandable path).

They did tell me they are suggesting people shall update to the latest version before moving to production (one problem is the bugs which are not fixed in their version, but by far the bigger problem is the outdated CCXT library - which may cause problems when connecting to exchanges).

**Comment by davideser** [comment]
hi, I have installed freqtrade, following docs and it has been successful.  I have done backtesting and now I am optimizing the strategy.

**Comment by xmatthias** [comment]
I will assume this as fixed by the above comments.

Let us know if that's not the case (you should still be able to comment below).

**Comment by aruncena123** [comment]
i followed the docs and initialized the user directory still getting an error and i am using gitbash terminal since docker is not installing in my pc.
![123](https://user-images.githubusercontent.com/39551652/81320601-138e7080-90af-11ea-85db-8c1f732c8d42.jpg)

**Comment by bhark** [comment]
@xmatthias I'm running into the exact same issue. Was able to fix it in my local instance by passing --strategy-path, but my cloud-hosted instance refuses to pick up any strategies.

**Comment by bhark** [comment]
I fixed it; it had to do with TA-lib not being installed correctly. I had to follow the manual installation steps [here](https://www.freqtrade.io/en/latest/installation/#install-ta-lib). The reason why it worked on my local machine, is that it's Arch btw, which sports a superior package manager, allowing me to install ta-lib system-wide.

**Comment by jamesjjcondon** [comment]
Same here. I've just done a fresh git clone and setup.sh . Seems to be an issue with ta dependency in docker only. Not an issue locally. Same with freqtrade:stable or develop image. Any pointers on how to fix in docker image?

```
freqtrade.resolvers.iresolver - WARNING - Could not import /freqtrade/user_data/strategies/Heracles.py due to 'No module named 'ta''
```

**Comment by xmatthias** [comment]
Some strategies require different requirements - which need to be installed.

for docker, this is documented [here](https://www.freqtrade.io/en/latest/docker_quickstart/#additional-dependencies-with-docker-compose) - but the dependencies will differ by strategy, so are obviously not covered.

**Comment by psilobits** [comment]
If anyone finds this error again and it was working prior to optimizing with HyperOpt, ensure no extra libraries were imported. I noticed `from msilib.schema import Condition` imported automatically which caused original posted error. This import is not needed.
