### ISSUE TITLE
Different backtest results when using informative pairs

### ISSUE THREAD

**Issue by ghost** [freqtrade/freqtrade#4255]
* Operating system: Docker Desktop MacOS 3.1.0 / Docker: 20.12.2 / Compose: 1.27.4 / image: freqtradeorg/freqtrade:master
  * Python Version:
  * CCXT version: 1.39.79
  * Freqtrade Version: 2020.12
  
For one of my strategies i am using multiple timeframes. I tried to modify this strategy to use informative pairs, but my backtest results are very much different when compared to resampling.

To analyse this further I wrote the merged dataframe to a csv file, for example the candle timestamps for a timeframe of 15 minutes, and informative pair of 1 day:

date: 2021-01-23 14:30:00+00:00, date_1d: 2021-01-21 00:00:00+00:00

This shows that the candle is being compared to the informative dataframe candle that is 2 days old. But it should be compared to the candle of 1 day ago, and I am quite sure this causes the difference in backtest results. When I compare the csv file of the merged dataframe with the json files in /userdata/data/, then it is clear that the last candle for both timeframes are not used.

In an older issue I found a reference to the last candle being dropped for backtesting: https://github.com/freqtrade/freqtrade/issues/1011#issuecomment-403912362

For the normal dataframe its not a problem that last candle is dropped. But this should probably not be applied to the informative dataframe when using multiple timeframes?

**Comment by xmatthias** [comment]
how are you combining the "real" and informative pairs?

Backtesting will always give you the full timerange, so the indicators are calculated across the full timerange at once.
Combining the 2 dataframes (dataframe + informative) correctly is left to the strategy (although we do provide a [helper method](https://www.freqtrade.io/en/latest/strategy-customization/#merge_informative_pair) to simplify this for users).

Using the "latest" value (`.iloc[-1]`) is something that the documentation clearly states as error .

**Comment by ghost** [comment]
Thank you for the quick follow up. I was indeed using the helper method. The relevant part of the strategy:

```python

class test_informative(IStrategy):

    timeframe = '15m'
    inf_tf = '1d'
    rsi_period = 14
    ma_short_period = 9
    ma_long_period = 21

    def informative_pairs(self):
        pairs = self.dp.current_whitelist()
        informative_pairs = [(pair, self.inf_tf) for pair in pairs]
        return informative_pairs

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=self.rsi_period)
        informative_df = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=self.inf_tf)
        informative_df['typ_price'] = ta.TYPPRICE(informative_df)
        informative_df['ma_short'] = ta.EMA(informative_df, price="typ_price", timeperiod=self.ma_short_period)
        informative_df['ma_long'] = ta.EMA(informative_df, price="typ_price", timeperiod=self.ma_long_period)
        informative_df.to_csv('user_data/informative-df-{}.csv'.format(metadata['pair'].replace("/","-")))
        dataframe = merge_informative_pair(dataframe, informative_df, self.timeframe, self.inf_tf, ffill=True)
        dataframe.to_csv('user_data/merged-df-{}.csv'.format(metadata['pair'].replace("/","-")))
        return dataframe

```
i could not attach csv files to this message, but converted it to excel. The merged data is for BTC-ETH pair on Binance, 15 minute and 1 day timeframes. I checked those against the json data, and both for the 15m and 1d timeframe the last line in the json file is not present in the used dataframes.

I just also noticed that the problem applies only to the last day. See lines 961/962 in the attached spreadsheet where i added some comments. Only today's data is wrong. This also means I can move forward to use the end date of yesterday for the backtest.

If there is any suggestion or other things to test, please let me know.
[merged-df-ETH-BTC.xlsx](https://github.com/freqtrade/freqtrade/files/5861982/merged-df-ETH-BTC.xlsx)

**Comment by xmatthias** [comment]
Well freqtrade will always just give you complete candles. 
Today's candle will complete at midnight, and will become available then. The same logic applies to regular dataframes, as well as to informative pairs.

The same applies to 15m candles (or all other timesframes) - but on longer timeframes it's easier to notice.

**Comment by xmatthias** [comment]
You should also give the new version a try - a bug in this regard was fixed in 2021.1 (or develop).

Let me know if that solves the issue so we can close this.

**Comment by ghost** [comment]
I have just checked the new version 2021.1, and last candle of the informative timeframe is still not correct. I expect last candle is skipped, and then with "ffill" during the merge the empty cells are filled with previous candle. I did an export of the informative dataframe before it is merged, and there the last available data was 3 Feb (1d candle), which is 2 days old

The new version also introduced a new issue, as the 1st candle of the informative timeframe is missing. The previous version did have this.

I did a dry run test from 29 Jan without end date ( --timerange=20210129- ). First a spreadsheet with the data after merging, 15m and 1d candles. See comments at rows 2/3 and 673/674. I have removed some of the columns with indicators, the relevant information is still there.
[merged-df-AAVE-USDT.xlsx](https://github.com/freqtrade/freqtrade/files/5931883/merged-df-AAVE-USDT.xlsx)

And next is the informative dataframe with only the 1d candles before the merging. Data already starts from 29 Nov 2020 and ends 3 Feb. Where I think it should also have 4 Feb (yesterday) as that data is available in the json files.
[informative-df-AAVE-USDT.xlsx](https://github.com/freqtrade/freqtrade/files/5931959/informative-df-AAVE-USDT.xlsx)

**Comment by xmatthias** [comment]
the merging IS correctly done.

Example screenshot:

![2021-02-05-192721_930x238_scrot](https://user-images.githubusercontent.com/5024695/107073866-2f62a680-67e8-11eb-91dd-2a11d77dddc9.png)

explanation: 
all dates are open dates - so the new candle (in this case, 2018-03-30) is available at the same time than the 2018-03-30 23:45:00) - as both of these candles have their close date at midnight.

----

your problem stems from data / missing data.
for the start problem - i'd in general always recommend to download more data than you need, and limit the backtest-range with `--timerange ...`.

That way, you'll have more data than what you need.

Backtesting up to today is problematic because of the data (not realted to merging itself).

To be sure that we're not storing incomplete candles, freqtrade will remove the last candle right after downloading.

It'll also remove the last candle on load (it's the default of the loading function) - but it's usually not a problem, as long as you have enough data at the end of the candle.
obviously, using daily candles this can be problematic as you'll miss a full day - but otherwise, it's not an issue.

Summary:
best don't backtest up to today, but backtest up to yesterday .

**Comment by ghost** [comment]
The end of the data is indeed fine when specifying the end date for the dry test. 

But regarding the missing data at the start, this has changed since new version 2021.1. I do not think it is an issue of missing data, but more likely has to do with alignment of data as explained further below. The export of the informative dataframe attached with previous message had candle data from 29 Nov 2020, where I was only doing a dry test for 1 week. 

I have just run the same strategy (--timerange=20210130-20210206) through version 2020.12 and 2021.1 and exported the merged data for further checking.

This is the merged dataframe for version 2020.12 where informative data is available in the first row.
[merged-df-AAVE-USDT-v2020_12.xlsx](https://github.com/freqtrade/freqtrade/files/5937228/merged-df-AAVE-USDT-v2020_12.xlsx)

And this is the merged dataframe for version 2021.1 where the informative data starts only at row 97.
[merged-df-AAVE-USDT-v2021_1.xlsx](https://github.com/freqtrade/freqtrade/files/5937229/merged-df-AAVE-USDT-v2021_1.xlsx)

I noticed there is a shift of 1 candle between the 2 versions. For example the start and end points for the 1 d candle of 2021-01-30 00:00:00+00:00 are as below:

in version 2020.12
start row 98 ( 2021-01-31 00:00:00+00:00 )
end row 193 ( 2021-01-31 23:45:00+00:00 )

version 2021.1
start row 97 ( 2021-01-30 23:45:00+00:00 )
end row 192 ( 2021-01-31 23:30:00+00:00 )

Which means that 2021.1 has the correct alignment of the candles. As you explained at midnight you indeed have the candle of 23:45 available for the normal dataframe, and also the candle for that previous day for the informative dataframe. Which is then also most likely the reason for the missing information at the start. For the informative candle of 29 January the normal dataframe would need to start at 29 Jan 23:45, but the start date of 30 Jan was used for the test.

After all, for my testing and strategy it is okay now. For the actual strategy I will probably not be using a 1d candle, most likely a 4h and then there is not much information missing. Most important is alignment of data which is correct in the new version.

**Comment by xmatthias** [comment]
yeah, you're correct, the "first" 23:45 candle will not be available for the "real" dataframe, so there's nothing to match it to.

It's the downside of the "right" matching way ... i wouldn't want to move the start-date of the backtest by 1 candle too (so instead of loading the 00:00 candle, load the 23:45 candle of the previous day - as that can become problematic when using longer timeframes (say i backtest 1D timeframes, i'm now suddenly disrespecting the user's wish and load 1 additional day.

**Comment by ghost** [comment]
I think its fine like it is now. Missing data at the start is not a problem, some of the indicators on the "real" dataframe also need a number of candles before they generate output. I understand what is happening. Thank you.
