### ISSUE TITLE
PerformanceWarning: DataFrame is highly fragmented.PerformanceWarning: DataFrame is highly fragmented.

### ISSUE THREAD

**Issue by LucianPopaLVP** [freqtrade/freqtrade#5408]
HI all!

## Describe your environment

  * Operating system: __Linux__
  * Python Version: __3.8___ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
Has anyone encountered this issue when backtesting/

py:1667: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  self.obj[key] = value

This is what i have found at py1667:

  # add a new item with the dtype setup
                        if com.is_null_slice(indexer[0]):
                            # We are setting an entire column
          py1667      self.obj[key] = value
                            return

what should i put here to make the backtesting work properly?
Thank you and appreciate your time!

**Comment by xmatthias** [comment]
It's just a warning that will not have real-world impacts on freqtrade.

It's caused by the way strategies are usually designed (insert one indicator after the other).

while this can be worked around, it's not worth the effort in my opinion, as it'll heavily reduce readability of your strategy.

**Comment by LucianPopaLVP** [comment]
> It's just a warning that will not have real-world impacts on freqtrade.
> 
> It's caused by the way strategies are usually designed (insert one indicator after the other).
> 
> while this can be worked around, it's not worth the effort in my opinion, as it'll heavily reduce readability of your strategy.

Thank you so much! I will just ignore it! Have a great day!

**Comment by Pascal66** [comment]
I've the same warning, but the impact is considerable when doing an hyperopt.
There's a billion of warning wich cause the output unreadable and maybe slowdown things

But it seems possible to mute this warning using this workaround : https://github.com/twopirllc/pandas-ta/issues/340#issuecomment-879450854 as it seems a panda issue

**Comment by xmatthias** [comment]
the pandas issue should be solved in pandas 1.3.1 - at least that's what they claimed in https://github.com/pandas-dev/pandas/issues/42477 
Best make sure that you've got an updated pandas version installed.

**Comment by Pascal66** [comment]
Still exist in panda 1.3.2
And something strange :
when I do `--spaces buy` or `--spaces sell` alone, warning **not happen**
when I do `--spaces buy sell` then the warning **happen**

**Comment by ghost** [comment]
@Pascal66 could you share a sample strategy that recreates the error?

I'm guessing it's due a loop that inserts into the dataframe many times e.g

```py
for i in self.buy_indicator_param.range:
   dataframe[i] = ta.indicator(dataframe, param = i)
```

which can be refactored to

```py
frames = [dataframe]
for i in self.buy_indicator_param.range:
   frame = DataFrame()
   frame[i] = ta.indicator(dataframe, param=i)
   frames.append(frame)
merged_frame = pd.concat(frames, axis=1)
```
but until there's a samples it will stay a guess.

**Comment by xmatthias** [comment]
it's a performance warning for sure - but i'm not convinced it actually matters for the way freqtrade uses the dataframe afterwards.
Also, freqtrade dataframes are comparably small comparing to what i've seen (and used) in other contexts - so i don't think the performance impact is actually something to worry about too much.

**Comment by Pascal66** [comment]
@LoveIsGrief perfect guess, thank you for the workaround

@xmatthias 
1) this affect performance, as writing to console a billion of time has a cost (in my side 20% gpu)
2) this make ouptut of hyperopt/backtesting unreadable
3) this happen only with --spaces buy sell, not with --spaces buy or --spaces sell, so there's a part of the code (not searched for now) making this warning

**Comment by ghost** [comment]
@Pascal66 I had to update the workaround (`return pd.concat(frames, axis=1`). Without `axis=1` it appends the new rows and column at `last_row + 1` and `last_column +1` (was able to see it due to backtesting and Pycharm's `DataFrame` view in debugging).

A notice on the workaround could be added to the docs, but I'm not sure if it will indeed be fixed in the new pandas version.

**Comment by neimad1985** [comment]
@LoveIsGrief Your workaround did fix the warning for me as well. Many thanks. +1 for adding this to the documentation (maybe just a pointer to @LoveIsGrief 's workaround in this issue if there is no time to write a complete section about the subject).

**Comment by ghost** [comment]
I added a repo to track the results of benchmarking the effects of modifying a dataframe. https://github.com/LoveIsGrief/pandas_bench

It's quickly thrown together, but should hopefully be indicative of whether the workaround is worth adding to the documentation or whether `PerformanceWarning` should simply be ignored. So far I've tested it on 4 machines and the workaround has been the fastest seeing time reductions up to 40% (it takes 60% of the time to run compared to without the workaround).

**Comment by skrew** [comment]
I have the same problem but i wanted a simple solution.
If you are using linux, simply add ` 2>&1 |grep -v PerformanceWarning|grep -v "self.obj"` to the end of the python command

**Comment by mcrumiller** [comment]
> ```python
> frames = [dataframe]
> for i in self.buy_indicator_param.range:
>    frame = DataFrame()
>    frame[i] = ta.indicator(dataframe, param=i)
>    frames.append(frame)
> merged_frame = pd.concat(frames, axis=1)
> ```

Doesn't this workaround cause the index to be replicated for each item in the list? In the event of a large shared `MultiIndex` this seems like it could be disastrous to performance.

**Comment by xmatthias** [comment]
i don't see this method as necessary in almost all cases anyway.

The performancewarning only applies within populate_indicators, as the dataframe is copied (at least in backtesting) when it's comming out of there.

**Comment by ginti-g** [comment]
Sorry, python newbie here :) Hi! I am having some issues with this matter.

I used the strategy example in the freqtrade website: https://www.freqtrade.io/en/stable/hyperopt/
and the hyperopt can run only some epochs (I think 8), then it crashes and gives this error:
PerformanceWarning: DataFrame is highly fragmented.

Then, I modified the code according to these instructions: https://www.freqtrade.io/en/latest/strategy-advanced/#performance-warning. This is the code:

`    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        frames = [dataframe]
        # Calculate all ema_short values
        for val in self.buy_ema_short.range:
            frames.append({
                f'ema_short_{val}': ta.EMA(dataframe, timeperiod=val)
            })

		# Calculate all ema_long values
        for val in self.buy_ema_long.range:
            frames.append({
                f'ema_long_{val}': ta.EMA(dataframe, timeperiod=val)
            })
        
        # Append columns to existing dataframe
        #merged_frame = pd.concat(frames, axis=1)

        #return dataframe
        return pd.concat(frames, axis=1)
`
But it results in the following error:
TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

Then I tried to implement this:
> 
> 
> @Pascal66 could you share a sample strategy that recreates the error?
> 
> I'm guessing it's due a loop that inserts into the dataframe many times e.g
> 
> ```python
> for i in self.buy_indicator_param.range:
>    dataframe[i] = ta.indicator(dataframe, param = i)
> ```
> 
> which can be refactored to
> 
> ```python
> frames = [dataframe]
> for i in self.buy_indicator_param.range:
>    frame = DataFrame()
>    frame[i] = ta.indicator(dataframe, param=i)
>    frames.append(frame)
> merged_frame = pd.concat(frames, axis=1)
> ```
> 
> but until there's a samples it will stay a guess.

and it works, but I have no idea of how to modify the following part:
`  def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = []
        conditions.append(qtpylib.crossed_above(
                dataframe[f'ema_short_{self.buy_ema_short.value}'], dataframe[f'ema_long_{self.buy_ema_long.value}']
            ))
        return dataframe
`

What should I write instead of `dataframe[f'ema_short_{self.buy_ema_short.value}'], dataframe[f'ema_long_{self.buy_ema_long.value}']`?

**Comment by mcrumiller** [comment]
@ginti-g :

I believe they have an error on their website.

```python
frames = [dataframe]
for val in self.buy_ema_short.range:
    frames.append({
        f'ema_short_{val}': ta.EMA(dataframe, timeperiod=val)
    })
```

They're making a list of single-valued dictionaries. What they instead meant to do is create a dataframe:
```python
frames = [dataframe]
for val in self.buy_ema_short.range:
    frames.append(pd.DataFrame({
        f'ema_short_{val}': ta.EMA(dataframe, timeperiod=val)
    }))
```

It would probably be best to create a list of `pd.Series` instead, although the overhead difference is probably negligible:
```python
frames = [dataframe]
for val in self.buy_ema_short.range:
    frames.append(pd.Series(
        ta.EMA(dataframe, timeperiod=val),
        name=f'ema_short_{val}'
    )
```

**Comment by xmatthias** [comment]
If hyperopt is crashing - then this has nothing to do with the PerformanceWarning.

As the warning states itself - a subsequent `.copy()` will mitigate the problem - which freqtrade is doing after `populate_indicators`.
Hyperopt will crash because it's running out of memory. You can find this in your system logs - and potential mitigations [in the documentation](https://www.freqtrade.io/en/latest/hyperopt/#out-of-memory-errors).
