### ISSUE TITLE
Crashing calculating the fees 

### ISSUE THREAD

**Issue by meechew** [freqtrade/freqtrade#6113]
## Describe your environment

  * Operating system: Debian GNU/Linux 11 \n \l
  * Python Version: 3.9.2
  * CCXT version: 1.65.2
  * Freqtrade Version: 2021.11
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Only when my FTX bot calculated fees it would crash. The other bots on other exchanges were fine.

### Steps to reproduce:

  1. Start bot.
  2. Wait till the order closed.
  
### Observed Results:

The bot would shut down. After some debugging, I found that `fee_rate_` was passed into `fee_rate_array` as a string.

### Work around:

changed freqtradebot.py:1411 to:
`fee_rate_array.append(float(fee_rate_))`

### Relevant code exceptions or logs

  File "/home/meechew/.local/lib/python3.9/site-packages/freqtrade/freqtradebot.py", line 1418, in fee_detection_from_trades
    fee_rate = sum(fee_rate_array) / float(len(fee_rate_array)) if fee_rate_array else None
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by xmatthias** [comment]
For now, i'm assigning this the "ccxt" label, as it's something that was changed in ccxt 9 days ago https://github.com/ccxt/ccxt/pull/10933.

If this is the new standard, we can adapt our code as it would impact other exchanges as well - but for the moment, i suspect it's a bug in the ftx implementation of ccxt.

**Comment by kroitor** [comment]
@xmatthias fixed in CCXT 1.65.21+, the new build will arrive in ~20 minutes. Thanks for your feedback!

**Comment by inyrface** [comment]
I am still encountering this issue in my docker build. How can I fix?

`docker-compose.yml`

```
version: '3'
services:
  freqtrade:
     #image: freqtradeorg/freqtrade:latest
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    image: ft_custom
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade1
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy
```

`Dockerfile.custom`

```
FROM freqtradeorg/freqtrade:develop

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# The below dependency - pyti - serves as an example. Please use whatever you need!
RUN pip install --user pyti
RUN pip install --user ta

# USER ftuser
```
