### ISSUE TITLE
Maintenance margin rate, Fatal exception

### ISSUE THREAD

**Issue by jeus1609** [freqtrade/freqtrade#7485]
## Describe your environment

  * Operating system: Win 10 21H2
  * Python Version: 3.10.4
  * CCXT version: 1.92.52
  * Freqtrade Version: 2022.8

CONFIG:
    "max_open_trades": 10,
    "stake_amount": "unlimited",
    "dry_run": true,
    Starting balance: 1000 USDT
    leverage: 8  (even thinking that it is the leverage I put by code that when there is no margin it returns leverage 1, but without 
 success)

## Describe the problem:

when the strategy chooses LUNA 2/USDT, 1000 LUNC/USDT, STG/USDT and a couple more that I don't remember, the bot stops working

### Observed Results:

-   leverage: 8 (even thinking that it is the leverage I put by code that when there is no margin it returns leverage 1, but without 
                    success)
-   I think that if it were for the margin of leverage then I should not start the trade

### Relevant code exceptions or logs

2022-09-26 16:26:49,725 - freqtrade.worker - INFO - Bot heartbeat. PID=204, version='2022.8', state='RUNNING'
2022-09-26 16:27:51,196 - freqtrade.worker - INFO - Bot heartbeat. PID=204, version='2022.8', state='RUNNING'
2022-09-26 16:28:10,165 - freqtrade.freqtradebot - INFO - Exit for LUNA2/USDT detected. Reason: roi
2022-09-26 16:28:11,965 - freqtrade.wallets - INFO - Wallets synced.
2022-09-26 16:28:12,372 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 32, 'exchange': 'Binance', 'pair': 'LUNA2/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 2.7149, 'order_type': 'limit', 'amount': 62.0, 'open_rate': 2.4274, 'close_rate': 2.7149, 'current_rate': 2.7149, 'profit_amount': 18.21433974, 'profit_ratio': 0.12100228, 'buy_tag': None, 'enter_tag': None, 'sell_reason': 'roi', 'exit_reason': 'roi', 'open_date': datetime.datetime(2022, 9, 24, 21, 30, 38, 500587), 'close_date': datetime.datetime(2022, 9, 26, 21, 28, 12, 372304), 'stake_amount': 150.4988, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2022-09-26 16:28:16,289 - freqtrade.wallets - INFO - Wallets synced.
2022-09-26 16:28:16,886 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=32, pair=LUNA2/USDT, amount=62.00000000, is_short=False, leverage=1.0, open_rate=2.42740000, open_since=2022-09-24 21:30:38)
2022-09-26 16:28:16,919 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=32, pair=LUNA2/USDT, amount=62.00000000, is_short=False, leverage=1.0, open_rate=2.42740000, open_since=2022-09-24 21:30:38) [sell]: 0.03366476 USDT - rate: 0.0002
2022-09-26 16:28:16,919 - freqtrade.persistence.trade_model - INFO - Updating trade (id=32) ...
2022-09-26 16:28:16,919 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=32, pair=LUNA2/USDT, amount=62.00000000, is_short=False, leverage=1.0, open_rate=2.42740000, open_since=2022-09-24 21:30:38).
2022-09-26 16:28:16,920 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=32, pair=LUNA2/USDT, amount=62.00000000, is_short=False, leverage=1.0, open_rate=2.42740000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2022-09-26 16:28:16,951 - freqtrade.commands.trade_commands - ERROR - Maintenance margin rate for LUNA2/USDT is unavailable for Binance
2022-09-26 16:28:16,951 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/freqtradebot.py", line 198, in process
    self.manage_open_orders()
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/freqtradebot.py", line 1205, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/freqtradebot.py", line 1734, in update_trade_state
    trade.set_liquidation_price(self.exchange.get_liquidation_price(
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/exchange/exchange.py", line 2450, in get_liquidation_price
    isolated_liq = self.get_or_calculate_liquidation_price(
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/exchange/exchange.py", line 2648, in get_or_calculate_liquidation_price
    isolated_liq = self.dry_run_liquidation_price(
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/exchange/binance.py", line 176, in dry_run_liquidation_price
    mm_ratio, maintenance_amt = self.get_maintenance_ratio_and_amt(pair, stake_amount)
  File "/mnt/c/Users/Johan/Desktop/freqtrade/freqtrade/exchange/exchange.py", line 2750, in get_maintenance_ratio_and_amt
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for LUNA2/USDT is unavailable for Binance
2022-09-26 16:28:16,997 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-09-26 16:28:16,997 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-09-26 16:28:17,345 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-09-26 16:28:17,349 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "9 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
2022-09-26 16:28:17,687 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-09-26 16:28:17,687 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2022-09-26 16:28:17,687 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-09-26 16:28:33,255 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.

**Comment by xmatthias** [comment]
Please provide us with the output of the following command (adjust to your database, obviously).

`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids 32`

**Comment by xmatthias** [comment]
Nevermind - (please next time mention that you're running on futures).

Binance has their leverage tiers (required information for trading) behind their API layer. As such, dry-run is required to use a cached version of this.
This means that for new (futures) pairs, an update is required.

LUNA2 is available in the develop version already - and i've just made another update (not relevant to this issue) - just to be sure we're uptodate.

**Comment by jeus1609** [comment]
Thank you very much for answering

**Comment by jeus1609** [comment]
Sorry for the inconvenience, I would like to know if there is a way to help with the code
It was solved with LUNA but now the problem came out again @xmatthias 

> 2022-10-04 10:13:58,882 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=74, pair=CVX/USDT, amount=42.31416786, is_short=False, leverage=1.0, open_rate=5.29800000, open_since=2022-10-04 15:12:57)
> 2022-10-04 10:13:58,897 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=74, pair=CVX/USDT, amount=42.31416786, is_short=False, leverage=1.0, open_rate=5.29800000, open_since=2022-10-04 15:12:57) [buy]: 0.0445032 USDT - rate: 0.0002
> 2022-10-04 10:13:58,897 - freqtrade.persistence.trade_model - INFO - Updating trade (id=74) ...
> 2022-10-04 10:13:58,898 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=74, pair=CVX/USDT, amount=42.00000000, is_short=False, leverage=1.0, open_rate=5.29800000, open_since=2022-10-04 15:12:57).
> 2022-10-04 10:13:58,910 - freqtrade.commands.trade_commands - ERROR - Maintenance margin rate for CVX/USDT is unavailable for Binance
> 2022-10-04 10:13:58,910 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
> Traceback (most recent call last):
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/commands/trade_commands.py", line 19, in start_trading
>     worker.run()
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/worker.py", line 74, in run
>     state = self._worker(old_state=state)
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/worker.py", line 114, in _worker
>     self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/worker.py", line 139, in _throttle
>     result = func(*args, **kwargs)
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/worker.py", line 152, in _process_running
>     self.freqtrade.process()
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/freqtradebot.py", line 198, in process
>     self.manage_open_orders()
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/freqtradebot.py", line 1205, in manage_open_orders
>     fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/freqtradebot.py", line 1734, in update_trade_state
>     trade.set_liquidation_price(self.exchange.get_liquidation_price(
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/exchange/exchange.py", line 2450, in get_liquidation_price
>     isolated_liq = self.get_or_calculate_liquidation_price(
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/exchange/exchange.py", line 2648, in get_or_calculate_liquidation_price
>     isolated_liq = self.dry_run_liquidation_price(
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/exchange/binance.py", line 176, in dry_run_liquidation_price
>     mm_ratio, maintenance_amt = self.get_maintenance_ratio_and_amt(pair, stake_amount)
>   File "/mnt/c/Users/Johan/Desktop/freqtrade/.env/lib/python3.10/site-packages/freqtrade/exchange/exchange.py", line 2750, in get_maintenance_ratio_and_amt
>     raise InvalidOrderException(
> freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for CVX/USDT is unavailable for Binance
> 2022-10-04 10:13:58,958 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit

DataBase

> [
>     {
>         "trade_id": 74,
>         "pair": "CVX/USDT",
>         "base_currency": "CVX",
>         "quote_currency": "USDT",       
>         "is_open": true,
>         "exchange": "binance",
>         "amount": 42.0,
>         "amount_requested": 42.31416786,
>         "stake_amount": 222.516,        
>         "strategy": "JovenJr",
>         "buy_tag": "buy_signal_rsi",    
>         "enter_tag": "buy_signal_rsi",  
>         "timeframe": 240,
>         "fee_open": 0.0002,
>         "fee_open_cost": 0.0445032,     
>         "fee_open_currency": "USDT",    
>         "fee_close": 0.0002,
>         "fee_close_cost": null,
>         "fee_close_currency": null,
>         "open_date": "2022-10-04 15:12:57",
>         "open_timestamp": 1664896377376,
>         "open_rate": 5.298,
>         "open_rate_requested": 5.298,
>         "open_trade_value": 222.5605032,
>         "close_date": null,
>         "close_timestamp": null,
>         "realized_profit": 0.0,
>         "close_rate": null,
>         "close_rate_requested": null,
>         "close_profit": null,
>         "close_profit_pct": null,
>         "close_profit_abs": null,
>         "trade_duration_s": null,
>         "trade_duration": null,
>         "profit_ratio": null,
>         "profit_pct": null,
>         "profit_abs": null,
>         "sell_reason": null,
>         "exit_reason": null,
>         "exit_order_status": null,
>         "stop_loss_abs": 1.166,
>         "stop_loss_ratio": -0.78,
>         "stop_loss_pct": -78.0,
>         "stoploss_order_id": null,
>         "stoploss_last_update": "2022-10-04 15:13:58",
>         "stoploss_last_update_timestamp": 1664896438910,
>         "initial_stop_loss_abs": 1.166,
>         "initial_stop_loss_ratio": -0.78,
>         "initial_stop_loss_pct": -78.0,
>         "min_rate": null,
>         "max_rate": 0.0,
>         "leverage": 1.0,
>         "interest_rate": 0.0,
>         "liquidation_price": null,
>         "is_short": false,
>         "trading_mode": "futures",
>         "funding_fees": 0.0,
>         "open_order_id": null,
>         "orders": [
>             {
>                 "amount": 42.0,
>                 "safe_price": 5.298,
>                 "ft_order_side": "buy",
>                 "order_filled_timestamp": 1664896438882,
>                 "ft_is_entry": true,
>                 "pair": "CVX/USDT",
>                 "order_id": "dry_run_buy_1664896377.010838",
>                 "status": "closed",
>                 "average": 5.298,
>                 "cost": 222.516,
>                 "filled": 42.0,
>                 "is_open": false,
>                 "order_date": "2022-10-04 15:12:57",
>                 "order_timestamp": 1664896377000,
>                 "order_filled_date": "2022-10-04 15:13:58",
>                 "order_type": "limit",
>                 "price": 5.298,
>                 "remaining": 0.0
>             }
>         ]
>     }
> ]

**Comment by xmatthias** [comment]
@jeus1609  check the version you're using.

based on the lines in the stacktrace, you're using 2022.8 - where this problem was not fixed yet.
