### ISSUE TITLE
ERROR - 'CandleType' is not a valid CandleType

### ISSUE THREAD

**Issue by owlswaper** [freqtrade/freqtrade#8217]
I create the config file and the strategy correctly, but by typing the command

freqtrade trade

I get this error :
```
2023-02-24 15:08:06,024 - freqtrade.commands.trade_commands - ERROR - 'CandleType' is not a valid CandleType
2023-02-24 15:08:06,024 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\Administrator\freqtrade\freqtrade\commands\trade_commands.py", line 25, in start_trading
    worker.run()
  File "C:\Users\Administrator\freqtrade\freqtrade\worker.py", line 75, in run
    state = self._worker(old_state=state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\freqtrade\freqtrade\worker.py", line 96, in _worker
    self.freqtrade.startup()
  File "C:\Users\Administrator\freqtrade\freqtrade\freqtradebot.py", line 181, in startup
    migrate_binance_futures_names(self.config)
  File "C:\Users\Administrator\freqtrade\freqtrade\util\binance_mig.py", line 29, in migrate_binance_futures_names
    migrate_binance_futures_data(config)
  File "C:\Users\Administrator\freqtrade\freqtrade\util\binance_mig.py", line 68, in migrate_binance_futures_data
    paircombs = dhc.ohlcv_get_available_data(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\freqtrade\freqtrade\data\history\idatahandler.py", line 56, in ohlcv_get_available_data
    return [
           ^
  File "C:\Users\Administrator\freqtrade\freqtrade\data\history\idatahandler.py", line 60, in <listcomp>
    CandleType.from_string(match[3])
  File "C:\Users\Administrator\freqtrade\freqtrade\enums\candletype.py", line 21, in from_string
    return CandleType(value)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\enum.py", line 695, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\enum.py", line 1111, in __new__
    raise ve_exc
ValueError: 'CandleType' is not a valid CandleType
```

**Comment by xmatthias** [comment]
From afar, it would appear like you've got something in your binance futures data directory ...

what does `dir user_data/data/binance/futures` show you?

**Comment by owlswaper** [comment]
> 

![Screenshot from 2023-02-24 16-33-14](https://user-images.githubusercontent.com/117394732/221185555-043a3fbe-a358-4d64-b4b0-f30935292208.png)

**Comment by xmatthias** [comment]
well now that's clearly wrong - and i'm not sure how these files were generated.
best remove these files - then the error should move away.


It should be noted that (while you didn't fill out the issue template) - i know you're using python3.11, which is not supported so far, and we didn't test against that so far.
so if you discover that these files come back after a new download, please try with a supported python version.

**Comment by owlswaper** [comment]
I deleted them and it was fixed, thank you

**Comment by duyns1110** [comment]
I also create the config file and the strategy then ran backtest correctly, but when I ran trade command I get this error.
I use python 3.10 and also try to re-download data but still get the same error

`2024-04-15 17:38:45,155 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2024-04-15 17:38:45,166 - freqtrade.commands.trade_commands - ERROR - 'C' is not a valid CandleType
2024-04-15 17:38:45,166 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/lenovo/Desktop/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/home/lenovo/Desktop/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "/home/lenovo/Desktop/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/home/lenovo/Desktop/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
  File "/home/lenovo/Desktop/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/home/lenovo/Desktop/freqtrade/freqtrade/freqtradebot.py", line 222, in process
    self.strategy.gather_informative_pairs())
  File "/home/lenovo/Desktop/freqtrade/freqtrade/strategy/interface.py", line 750, in gather_informative_pairs
    informative_pairs = [
  File "/home/lenovo/Desktop/freqtrade/freqtrade/strategy/interface.py", line 751, in <listcomp>
    (p[0], p[1], CandleType.from_string(p[2]) if len(
  File "/home/lenovo/Desktop/freqtrade/freqtrade/enums/candletype.py", line 24, in from_string
    return CandleType(value)
  File "/home/lenovo/anaconda3/envs/freqtrade3.10/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/home/lenovo/anaconda3/envs/freqtrade3.10/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'C' is not a valid CandleType
2024-04-15 17:38:45,170 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2024-04-15 17:38:45,170 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2024-04-15 17:38:45,170 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-04-15 17:38:45,171 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
`

**Comment by xmatthias** [comment]
@duyns1110 sounds a bit like you've got a syntax error somewhere.

Without the actual code used for informative pairs that's difficult to tell.
i'd want you to open your own issue describing your environment and what you're trying to do. 
it's NOT the same issue as this one - hence does not belong here. Thanks

**Comment by duyns1110** [comment]
thank you, I will post this error as a new issue
